<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'Gift Box',
                'price' => 9.99,
                'image' => 'products/box.jpeg',
                'amount' => 50,
                'Category_id' => 2,
                'shop_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Butterfly Bracelet',
                'price' => 19.99,
                'image' => 'products/bracelet.jpeg',
                'amount' => 50,
                'Category_id' => 2,
                'shop_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Happy Gloves',
                'price' => 9.99,
                'image' => 'products/gloves.jpeg',
                'amount' => 50,
                'Category_id' => 2,
                'shop_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Puff Vest',
                'price' => 29.99,
                'image' => 'products/hoodie.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Puff jacket',
                'price' => 29.99,
                'image' => 'products/hoodie2.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baige Coat',
                'price' => 29.99,
                'image' => 'products/pijama.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Heart Necklace',
                'price' => 19.99,
                'image' => 'products/ship.jpeg',
                'amount' => 50,
                'Category_id' => 2,
                'shop_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Black T-Shirt',
                'price' => 29.99,
                'image' => 'products/shirt.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Running Shoes',
                'price' => 29.99,
                'image' => 'products/shoes.jpeg',
                'amount' => 50,
                'Category_id' => 3,
                'shop_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Puma Jordans',
                'price' => 29.99,
                'image' => 'products/shoes2.jpeg',
                'amount' => 50,
                'Category_id' => 3,
                'shop_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Puma Sneackers',
                'price' => 29.99,
                'image' => 'products/shoes3.jpeg',
                'amount' => 50,
                'Category_id' => 3,
                'shop_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gray Air Jordans',
                'price' => 29.99,
                'image' => 'products/shoes4.jpeg',
                'amount' => 50,
                'Category_id' => 3,
                'shop_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Black Running Adidas ',
                'price' => 29.99,
                'image' => 'products/shoes5.jpeg',
                'amount' => 50,
                'Category_id' => 3,
                'shop_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Casual Pumas',
                'price' => 29.99,
                'image' => 'products/shoes6.jpeg',
                'amount' => 50,
                'Category_id' => 3,
                'shop_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SuperStar Adidas',
                'price' => 29.99,
                'image' => 'products/shoes7.jpeg',
                'amount' => 50,
                'Category_id' => 3,
                'shop_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Black Running Nike',
                'price' => 29.99,
                'image' => 'products/shoes8.jpeg',
                'amount' => 50,
                'Category_id' => 3,
                'shop_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Casual Nike',
                'price' => 29.99,
                'image' => 'products/shoes9.jpeg',
                'amount' => 50,
                'Category_id' => 3,
                'shop_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stand Souvinre',
                'price' => 4.99,
                'image' => 'products/stand.jpeg',
                'amount' => 50,
                'Category_id' => 2,
                'shop_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stickers collection #1',
                'price' => 9.99,
                'image' => 'products/stickers.jpeg',
                'amount' => 50,
                'Category_id' => 2,
                'shop_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stickers collection #2',
                'price' => 9.99,
                'image' => 'products/stickers2.jpeg',
                'amount' => 50,
                'Category_id' => 2,
                'shop_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stickers collection #3',
                'price' => 9.99,
                'image' => 'products/stickers3.jpeg',
                'amount' => 50,
                'Category_id' => 2,
                'shop_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rose Gold Watch',
                'price' => 19.99,
                'image' => 'products/watch.jpeg',
                'amount' => 50,
                'Category_id' => 2,
                'shop_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blue Jeans',
                'price' => 19.99,
                'image' => 'products/tshirt.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baseball Jacket',
                'price' => 19.99,
                'image' => 'products/tshirt2.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Boyfriend Jeans',
                'price' => 29.99,
                'image' => 'products/pants.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leather Jacket',
                'price' => 39.99,
                'image' => 'products/jacket.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Black Sweater',
                'price' => 29.99,
                'image' => 'products/sweater.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gray Jacket',
                'price' => 29.99,
                'image' => 'products/jacket2.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'F1 Boss Jacket',
                'price' => 29.99,
                'image' => 'products/jacket4.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Song Name T-Shirt',
                'price' => 29.99,
                'image' => 'products/jacket5.jpeg',
                'amount' => 50,
                'Category_id' => 1,
                'shop_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
